### ISSUE TITLE
Support Firebase Admin SDK v10

### ISSUE THREAD

**Issue by dhkatz** [anishkny/integrify#116]
There doesn't appear to be support for the newer v10 SDK. Would be nice to be able to use integrity with it.

**Comment by anishkny** [comment]
Thanks for opening this. Upgrading `firebase-tools` to v10 seems to cause:

```
Error: `runtime` field is required but was not found in firebase.json.
To fix this, add the following lines to the `functions` section of your firebase.json:
"runtime": "nodejs16"
```

Working on a fix.

**Comment by dhkatz** [comment]
I also believe that my GitHub action for deploying functions was also complaining about invalid peer dependency for integrity, stating that my version was too new for it to work (understandably)

**Comment by anishkny** [comment]
Fixed by #118 & #119.

@dhkatz Please upgrade to [v4.0.4](https://github.com/anishkny/integrify/blob/main/CHANGELOG.md#404-2022-04-19) and reopen if it doesn't work!

**Comment by dhkatz** [comment]
@anishkny It appears to be working at least in the emulator suite so far.

TypeScript is complaining, however, about the overloads generated for the `integrify` function.

It seems the Rule interface only specifies the actual `rule` field (and an optional `name`).

Example:

```typescript
export const replUserAttrs = integrify({
	rule: 'REPLICATE_ATTRIBUTES',
	source: {
		collection: 'users',
	},
	targets: [
		{
			collection: 'profiles',
			foreignKey: 'userId',
			attributeMapping: {
				role: 'role',
			},
		},
	],
});
```

Error:

```
TS2769: No overload matches this call.   
Overload 1 of 3, '(config: Config): null', gave the following error.     
    Argument of type '{ rule: string; source: { collection: string; }; targets: { collection: string; foreignKey: string; attributeMapping: { role: string; }; }[]; }' is not assignable to parameter of type 'Config'. 
    Object literal may only specify known properties, and 'rule' does not exist in type 'Config'.   
Overload 2 of 3, '(rule: Rule): IntegrifyFunction', gave the following error.     
    Argument of type '{ rule: "REPLICATE_ATTRIBUTES"; source: { collection: string; }; targets: { collection: string; foreignKey: string; attributeMapping: { role: string; }; }[]; }' is not assignable to parameter of type 'Rule'.       
    Object literal may only specify known properties, and 'source' does not exist in type 'Rule'.
```

Fix:

I see you extend the interface for each type of rule, you might have to invert the definition. i.e:

```typescript
type Rule = { name?: string } & (ReplicateAttributesRule | MaintainCountRule | DeleteReferencesRule);
```

Then add each `rule` field to each interface itself. I think this will let TypeScript infer which type of rule you're using too and provide type hints for that specific interface which is nice.

**Comment by dhkatz** [comment]
Here's a [TypeScript Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCIQDYUgJQjaCEJAZxwFctkBvAWAChlkpKIAuZAclQFEAZHgBUeAfRw8AYj3EA5AMI8AypwDcDJiQD25KEg51GTZAk0YsCMME0gOJMFFABzNYYC+LpmDhRH2EvvUjEzMICysbZDsHEGdAphhNKAhgRxAAaQgAT1t7Jw8jYBI5U3NLawBxKG0ABwB+DgAjTVMIOBB81wBtAF18gAtmgGsSepo45AB6CeQIEgxQMABaABNCuAasRZAIAA8l+e3kAAEwTOrZhAdqpdmDsAmGtsXT85Jx6qTRiXJiMvbA9wMVwMBgLaDwJDIPDVeYIOCQACCYFyDXIkDIrDGhhYWA4nHEAAU+ABJOQI4QicmCHDEgBCAFVhMp8lodHosUZjCVQn8ctFYm58l4fH4AoYmMFSuE+Xlxgkkil0lkZTF8kx4Si0RAALJwarVJxizlMTqs3QQJGayAqxzdG1q5CA8XIQrFEJhCpVch1RrNLBtDo9fpDEZGoxTGZzBYrNYbCBbXb7UAoE5nC5XG5R8APJ4vWbvT4cb6-cIdFzA+ig8DgxAoXULOCgYo-MAUKgGJg49hcbUI4kyQR9mQiOQAeXpA9UgTN7I7QW5HoiUVlzvlyVSGWykVyqoBQu8vjAYYlC952-5Do1DlR1vPK6YTorDDzUMxAF4aMgQHAALYQUbLjEjrIAAZMgAAU6BYLg+CEMQsxtigAA+UIQDCwBwoiyLXlqGJUCh9bgI2IDNuAiEAJQgvQMA-IuLrVo4DgwJk4FdhwFEcG0mRYgAkMAMAQV2AB0XbIG+4lcISJJkhSVI0gyTKcORvE8RGghpoolzANc9EEFAJDIHABnQrC8IWthwA3ghrAMDxrgzBgJAoPxgmsCJ74Sdw-BCKI4hSLICjKMpBg8ap0zqecmkZrp0AGUZaCYNgEB4HpRCkIhtn2ZgTkqRGACa2hcpQyzIMsmgOTl-EADTIDeyARRAUXaWAMX6YZGBJHAyzcfFhFeE22hkTZ9B2UCVFgox-EsSFbGSTwRKkuSohyXSjJKJwVW2RGMiaAA7sgu0oIeXKmMgL6gKl8HIPKyAfJo5xQJYszIJoAkmRhZmWjh6IZSN22aJYkJgH0KDQFUUBAuRQA) of what I'm talking about
