### ISSUE TITLE
Question: Can the source be a collection group?

### ISSUE THREAD

**Issue by anishkny** [anishkny/integrify#56]
Initially asked [here](https://github.com/anishkny/integrify/issues/22#issuecomment-647865400) by @devth.

I believe you should be able to get away with defining wildcard subcollections for `rule.source.collection` as defined [here](https://firebase.google.com/docs/functions/firestore-events#wildcards-parameters).

The value of `rule.source.collection` is used thus: https://github.com/anishkny/integrify/blob/f0d7a09ec3eb07c8ad59eeb5170b654eb72cacd2/src/rules/replicateAttributes.ts#L52

**Comment by devth** [comment]
@anishkny thank you! I will try this. And thanks for this awesome lib!
