### ISSUE TITLE
replicate to nested destination

### ISSUE THREAD

**Issue by alvin** [anishkny/integrify#9]
Hell @anishkny,

Love this architecture and approach, using it already on my latest project!

Question - is it possible (or hard to add) the ability to target a _nested_ property for replication?

My use-case is a "users" collection that is essentially private, and a "workspaces" collection that has an array of memberIds.   

I'd like to use integrify to update a memberInfo object on workspaces, keyed by uid, with just the user's name and avatar.

So the source is a users collection and target looks something like:

```
workspaces: [{
   id: "some guid",
   memberIds: ["firebaseUid1","firebaseUid2"], <--- this is currently how users are added/removed to workspaces
   memberInfoCache: {  <--- I'd like to add meta info cache to avoid complicated permissions on accessing /users/
       "firebaseUid1": { <--- the foreign key
           "photoURL": "replicated from users/firebaseUid1/photoURL",
           "name": "replicated from users/firebaseUid1/name"
       },
       ...
    }
}]

```

**Comment by anishkny** [comment]
First of all thanks for the kind words and I'm glad this is useful!

The main issue supporting this use case (right now) is that Firestore does not allow querying across multiple subcollections (in your case `memberInfoCache`). See [here](https://firebase.google.com/docs/firestore/manage-data/structure-data#subcollections).

Although I have heard this may be on the Firestore roadmap ([source](https://stackoverflow.com/questions/46573014/firestore-query-subcollections)). Once this is supported, I feel it would make sense for `integrify` to support this scenario.

One workaround is to structure `memberInfoCache` as a root level collection having `workspaceId` as a foreign key.

```
workspaces/
  workspaceId/
    <workspace data>

memberships/
  <some_uuid>/
    workspaceId
    firebaseUid   <--- foreign key
    photoURL      <--- replicated
    name          <--- replicated

users/
  firebaseUid/
    photoURL
    name
```

```
integrify({
  rule: 'REPLICATE_ATTRIBUTES',
  source: {
    collection: 'users',
  },
  targets: [
    {
      collection: 'memberships',
      foreignKey: 'firebaseUid',
      attributeMapping: {
        photoURL: 'photoURL',
        name: 'name',
      },
    },
  ],
})
```

**Comment by alvin** [comment]
Thanks so much.  I did think of something along those lines, but am trying to avoid extra querying, for example on a list of the workspaces that a user is a member of, I'd like the information to live right inside the actual workspace document.

My proposal is a nested object property within the document, rather than a subcollection.  I realize this will place limitations on the ultimate size of the base document, but I am comfortable with this constraint.  I just looked it up and firestore calls this a "map" -- so I guess I'm looking for a nested map, more like the original firebase db, I suppose.

![image](https://user-images.githubusercontent.com/16319/52799273-5a1d2880-302e-11e9-8166-155325c93a93.png)

The other factor that came to mind is needing the backend process  to sync users over to the cache not only when they are updated, but also when members are added to the workspace.  So perhaps a root level connection that shares the same guid as the workspace does make sense, if it can be set it up two ways somehow.

Thanks again for your thoughts

**Comment by anishkny** [comment]
I am going to hold off for now in the hopes that Firestore supports "collection group queries" eventually. That should make implementation easier/elegant. Will leave issue open for now.

**Comment by anishkny** [comment]
Update: looks like this is now supported https://firebase.google.com/docs/firestore/query-data/queries#collection-group-query

**Comment by anishkny** [comment]
This has now landed in `master`. Feel free to replicate to nested destinations thus:

```js
module.exports.replicateMasterToDetail = integrify({
  rule: 'REPLICATE_ATTRIBUTES',
  source: {
    collection: 'master',
  },
  targets: [
    {
      collection: 'subcollection',
      foreignKey: 'masterId',
      attributeMapping: {
        masterField1: 'detail1Field1',
      },
    },
    isCollectionGroup: true,    // <---- NEWLY ADDED!
  ],
  
```
